# Generated by Django 6.0.6 on 2026-06-09 20:56

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_navigation_footer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footersettings',
            name='footer_links',
            field=wagtail.fields.StreamField([('link', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Choose a page on this site.', 'label': 'Internal page', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'External URL or relative path. Used when no page is selected.', 'label': 'URL', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('label', 0), ('page', 1), ('url', 2)]], {})}),
        ),
        migrations.AlterField(
            model_name='footersettings',
            name='legal_links',
            field=wagtail.fields.StreamField([('link', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Choose a page on this site.', 'label': 'Internal page', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'External URL or relative path. Used when no page is selected.', 'label': 'URL', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('label', 0), ('page', 1), ('url', 2)]], {})}, help_text='Privacy, Terms, Cookies, and other legal links shown in the footer bottom row.'),
        ),
        migrations.AlterField(
            model_name='navigationsettings',
            name='nav_links',
            field=wagtail.fields.StreamField([('link', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Choose a page on this site.', 'label': 'Internal page', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'External URL or relative path. Used when no page is selected.', 'label': 'URL', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('label', 0), ('page', 1), ('url', 2)]], {})}),
        ),
    ]
