# Generated by Django 6.0.6 on 2026-06-09 21:51

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_update_footer_legal_links'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footersettings',
            name='legal_links',
            field=wagtail.fields.StreamField([('link', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Choose a page on this site.', 'label': 'Internal page', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'External URL or relative path. Used when no page is selected.', 'label': 'URL', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('label', 0), ('page', 1), ('url', 2)]], {})}, help_text='Privacy, Terms, and other legal links shown in the footer bottom row.'),
        ),
        migrations.CreateModel(
            name='CookieConsentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Show the cookie consent banner on the public site.')),
                ('message', models.TextField(default='We use cookies to improve your experience and analyze site traffic.')),
                ('accept_button_text', models.CharField(default='Accept All', max_length=50)),
                ('decline_button_text', models.CharField(default='Decline', max_length=50)),
                ('learn_more_link', wagtail.fields.StreamField([('link', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Choose a page on this site.', 'label': 'Internal page', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'External URL or relative path. Used when no page is selected.', 'label': 'URL', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('label', 0), ('page', 1), ('url', 2)]], {})}, help_text='Optional link to the privacy policy (or other policy page).')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Cookie consent',
            },
        ),
    ]
