# Generated by Django 6.0.6 on 2026-06-09 20:40

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('hero', 7), ('tabs', 12), ('feature', 17), ('cards', 24), ('va_section', 29), ('testimonial', 30), ('stats', 34), ('cta', 36), ('promo', 38), ('rich_text', 14), ('faq', 42)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.blocks.URLBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.blocks.URLBlock', (), {'required': False}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'default': 'Hero background', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subheading', 1), ('primary_button_text', 0), ('primary_button_url', 2), ('secondary_button_text', 3), ('secondary_button_url', 4), ('background_image', 5), ('background_image_alt', 6)]], {}), 8: ('wagtail.blocks.TextBlock', (), {'required': False}), 9: ('wagtail.blocks.CharBlock', (), {'default': 'programs', 'required': False}), 10: ('wagtail.blocks.StructBlock', [[('tab_label', 0), ('heading', 0), ('body', 1), ('button_text', 3), ('button_url', 4), ('image', 5)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {}), 12: ('wagtail.blocks.StructBlock', [[('section_heading', 3), ('section_subheading', 8), ('section_id', 9), ('tabs', 11)]], {}), 13: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('right', 'Right')]}), 14: ('core.blocks.RichTextBlock', (), {}), 15: ('wagtail.blocks.CharBlock', (), {'default': "What you'll achieve", 'required': False}), 16: ('wagtail.blocks.ListBlock', (0,), {'required': False}), 17: ('wagtail.blocks.StructBlock', [[('image', 5), ('image_position', 13), ('heading', 0), ('subheading', 8), ('body', 14), ('outcomes_heading', 15), ('outcomes', 16), ('button_text', 3), ('button_url', 4)]], {}), 18: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('2', '2'), ('3', '3'), ('4', '4')]}), 19: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('default', 'Default cards'), ('accreditation', 'Standards & organizations'), ('pillar', 'Organizational pillars')]}), 20: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. accet.org — shown on accreditation cards', 'required': False}), 21: ('wagtail.blocks.BooleanBlock', (), {'default': False, 'required': False}), 22: ('wagtail.blocks.StructBlock', [[('icon', 5), ('heading', 0), ('body', 1), ('link_text', 3), ('link_url', 4), ('link_meta', 20), ('external_link', 21)]], {}), 23: ('wagtail.blocks.ListBlock', (22,), {}), 24: ('wagtail.blocks.StructBlock', [[('section_heading', 3), ('section_subheading', 8), ('columns', 18), ('style', 19), ('cards', 23)]], {}), 25: ('wagtail.blocks.RichTextBlock', (), {}), 26: ('wagtail.blocks.CharBlock', (), {'default': 'va-accelerator', 'required': False}), 27: ('wagtail.blocks.StructBlock', [[('heading', 0), ('body', 1), ('button_text', 3), ('button_url', 4)]], {}), 28: ('wagtail.blocks.ListBlock', (27,), {}), 29: ('wagtail.blocks.StructBlock', [[('heading', 0), ('highlight', 25), ('intro', 8), ('section_id', 26), ('subsections', 28)]], {}), 30: ('wagtail.blocks.StructBlock', [[('quote', 1), ('author_name', 3), ('author_title', 3), ('author_image', 5), ('prominent', 21)]], {}), 31: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('shield', 'Shield — Anticipate'), ('lightning', 'Lightning — Respond'), ('clock', 'Clock — Recover'), ('chart', 'Chart — Sustain')]}), 32: ('wagtail.blocks.StructBlock', [[('label', 0), ('icon', 31)]], {}), 33: ('wagtail.blocks.ListBlock', (32,), {}), 34: ('wagtail.blocks.StructBlock', [[('heading', 3), ('items', 33)]], {}), 35: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'help_text': 'Use full-width CTA band styling', 'required': False}), 36: ('wagtail.blocks.StructBlock', [[('heading', 0), ('subheading', 8), ('primary_button_text', 0), ('primary_button_url', 2), ('secondary_button_text', 3), ('secondary_button_url', 4), ('band_style', 35)]], {}), 37: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('light', 'Light'), ('dark', 'Dark'), ('accent', 'Accent')]}), 38: ('wagtail.blocks.StructBlock', [[('badge_text', 3), ('heading', 0), ('body', 14), ('button_text', 3), ('button_url', 4), ('background_style', 37)]], {}), 39: ('wagtail.blocks.CharBlock', (), {'default': 'Frequently Asked Questions', 'required': False}), 40: ('wagtail.blocks.StructBlock', [[('question', 0), ('answer', 14)]], {}), 41: ('wagtail.blocks.ListBlock', (40,), {}), 42: ('wagtail.blocks.StructBlock', [[('heading', 39), ('items', 41)]], {})})),
            ],
            options={
                'verbose_name': 'Flexible Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='LegalPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True)),
                ('compliance_badges', wagtail.fields.StreamField([('badge', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.blocks.StructBlock', [[('label', 0), ('description', 1)]], {})})),
                ('last_updated', models.DateField(blank=True, null=True)),
                ('body', wagtail.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Legal Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
